name: Docker Build and Push

on:
  push:
    branches: [main] # Trigger the workflow on pushes to the main branch (adjust as needed)
  pull_request:
    branches: [main] # Trigger on pull requests to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest # Use an Ubuntu runner (you can use other runners too)
    permissions:
      contents: read
      packages: write # Required for pushing to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -t your-github-username/your-repository-name:latest . # Replace with your details

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }} # Use the GITHUB_TOKEN secret

      - name: Push the Docker image
        run: docker push your-github-username/your-repository-name:latest # Replace with your details
