name: Docker Build, Run & Test in GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-run-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name my-running-app my-app
          sleep 5  # Wait for the container to start

      - name: Install Prettier inside the container
        run: |
          docker exec my-running-app npm install -g prettier@3.4.2

      - name: Ensure test file exists
        run: |
          docker exec my-running-app sh -c "echo '# Sample Markdown' > /data/format.md"

      - name: Test API: Format Markdown
        run: |
          curl -X POST -H "Content-Type: application/json" \
          -d '{"task": "/data/format.md needs to be formatted using prettier@3.4.2, updating the file in-place"}' \
          http://localhost:8000/run_task

      - name: Stop & Remove Container
        if: always()
        run: |
          docker stop my-running-app
          docker rm my-running-app
