name: Docker Build and Push

on:
  push:
    branches: [main]  # Trigger on pushes to the main branch
  pull_request:
    branches: [main]  # Trigger on pull requests to main

jobs:
  build-and-push:
    runs-on: ubuntu-latest  # Use an Ubuntu runner
    permissions:
      contents: read
      packages: write  # Required for pushing to GitHub Packages

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the Docker image
        run: |
          IMAGE_NAME="ghcr.io/${{ github.repository_owner }}/dataworks-project:latest"
          docker build -t $IMAGE_NAME .
          docker push $IMAGE_NAME
