name: Docker Build, Run & Test in GitHub Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-run-test:
    runs-on: ubuntu-latest  # Runs on GitHub-hosted Ubuntu machine

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker Image
        run: |
          docker build -t my-app .

      - name: Run Docker Container
        run: |
          docker run -d -p 8000:8000 --name my-running-app my-app
          sleep 5  # Wait for container to start

      - name: Test if API is Running
        run: |
          curl --retry 5 --retry-connrefused http://localhost:8000/run?task=test

      - name: Stop & Remove Container
        if: always()
        run: |
          docker stop my-running-app
          docker rm my-running-app
